# Generated by Django 5.0.3 on 2024-03-27 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("booking", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="showseason",
            name="astronomy_show",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="booking.astronomyshow",
            ),
        ),
        migrations.AddField(
            model_name="showseason",
            name="planetarium_dome",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="booking.planetariumdome",
            ),
        ),
        migrations.AddField(
            model_name="astronomyshow",
            name="show_theme",
            field=models.ManyToManyField(
                blank=True,
                related_name="astronomy_shows",
                to="booking.showtheme",
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="reservation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tickets",
                to="booking.reservation",
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="show_season",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tickets",
                to="booking.showseason",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="ticket",
            unique_together={("show_season", "row", "seat")},
        ),
    ]
